pipeline {
    agent any
    
    environment {
        DOCKER_IMAGE = "go-hello-world"
        DOCKER_TAG = "latest"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/clerikc/ferstprojekt.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('my-go-app') {
                    script {
                        // Создаем go.mod если его нет
                        sh '''
                            if [ ! -f go.mod ]; then
                                go mod init hello-world
                            fi
                            go mod tidy
                        '''
                        
                        // Сборка образа с использованием Docker Pipeline
                        docker.build("${DOCKER_IMAGE}:${DOCKER_TAG}")
                    }
                }
            }
        }

        stage('Run Container') {
            steps {
                script {
                    // Останавливаем и удаляем старый контейнер
                  //  sh 'docker stop hello-container || true'
                   // sh 'docker rm hello-container || true'
                    
                    // Запускаем контейнер через shell-команду
                    sh "docker run --name hello-container -p 9090:9090 -d ${DOCKER_IMAGE}:${DOCKER_TAG}"
                }
            }
        }
    }

    post {
        always {
            echo 'Cleaning up...'
        }
        success {
            echo 'Application is running at: http://localhost:9090'
        }
    }
}