pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "go-hello-world"
        DOCKER_TAG = "latest"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', 
                     url: 'https://github.com/clerikc/ferstprojekt.git'
            }
        }

        stage('Build and Run Docker') {
            steps {
                script {
                    sh 'cd my-go-app & go mod init hello-world || true'
                sh 'cd my-go-app & go mod tidy'
                
                    // Собираем образ
                    docker.build("${DOCKER_IMAGE}:${DOCKER_TAG}", "--file my-go-app/Dockerfile .")
                    
                    // Останавливаем и удаляем старый контейнер
                   // sh 'docker stop hello-container || true'
                    //sh 'docker rm hello-container || true'
                    
                    // Запускаем новый контейнер
                sh "docker run --name hello-container -p 9090:9090 -d ${DOCKER_IMAGE}:${DOCKER_TAG}"
                }
            }
        }
    }

    post {
        always {
            echo 'Cleaning up...'
        }
        success {
            echo 'Docker container is running!'
            echo "Access at: http://${env.DOCKER_HOST ?: 'localhost'}:9090"
        }
    }
}